.PHONY:

# etcd

etcd-cluster-run:
	docker-compose -f build/docker-compose.yml up -d 

etcd-cluster-stop:
	docker-compose -f build/docker-compose.yml stop

etcd-cluster-rm:
	docker-compose -f build/docker-compose.yml rm